/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from 'ethers';
import type { FunctionFragment, Result, EventFragment } from '@ethersproject/abi';
import type { Listener, Provider } from '@ethersproject/providers';
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from '../../../common/types/CommonContractTypes';

export interface MarketplaceInterface extends utils.Interface {
  functions: {
    'buyItem(uint256)': FunctionFragment;
    'changeItemStatus(uint256,bool)': FunctionFragment;
    'feePercent()': FunctionFragment;
    'getContractBalance()': FunctionFragment;
    'getItemsCount()': FunctionFragment;
    'getItemsSold()': FunctionFragment;
    'getTotalPrice(uint256)': FunctionFragment;
    'items(uint256)': FunctionFragment;
    'itemsCount()': FunctionFragment;
    'itemsSold()': FunctionFragment;
    'makeItem(address,uint256,uint256)': FunctionFragment;
    'owner()': FunctionFragment;
    'renounceOwnership()': FunctionFragment;
    'setFeePercent(uint256)': FunctionFragment;
    'transferOwnership(address)': FunctionFragment;
    'withdraw()': FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | 'buyItem'
      | 'changeItemStatus'
      | 'feePercent'
      | 'getContractBalance'
      | 'getItemsCount'
      | 'getItemsSold'
      | 'getTotalPrice'
      | 'items'
      | 'itemsCount'
      | 'itemsSold'
      | 'makeItem'
      | 'owner'
      | 'renounceOwnership'
      | 'setFeePercent'
      | 'transferOwnership'
      | 'withdraw'
  ): FunctionFragment;

  encodeFunctionData(functionFragment: 'buyItem', values: [PromiseOrValue<BigNumberish>]): string;
  encodeFunctionData(
    functionFragment: 'changeItemStatus',
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<boolean>]
  ): string;
  encodeFunctionData(functionFragment: 'feePercent', values?: undefined): string;
  encodeFunctionData(functionFragment: 'getContractBalance', values?: undefined): string;
  encodeFunctionData(functionFragment: 'getItemsCount', values?: undefined): string;
  encodeFunctionData(functionFragment: 'getItemsSold', values?: undefined): string;
  encodeFunctionData(
    functionFragment: 'getTotalPrice',
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(functionFragment: 'items', values: [PromiseOrValue<BigNumberish>]): string;
  encodeFunctionData(functionFragment: 'itemsCount', values?: undefined): string;
  encodeFunctionData(functionFragment: 'itemsSold', values?: undefined): string;
  encodeFunctionData(
    functionFragment: 'makeItem',
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
  encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
  encodeFunctionData(
    functionFragment: 'setFeePercent',
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: 'transferOwnership',
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(functionFragment: 'withdraw', values?: undefined): string;

  decodeFunctionResult(functionFragment: 'buyItem', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'changeItemStatus', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'feePercent', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'getContractBalance', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'getItemsCount', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'getItemsSold', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'getTotalPrice', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'items', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'itemsCount', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'itemsSold', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'makeItem', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'setFeePercent', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
  decodeFunctionResult(functionFragment: 'withdraw', data: BytesLike): Result;

  events: {
    'LogBuyItem(uint256,address,uint256,uint256,address,address)': EventFragment;
    'LogChangeStatus(uint256,address,bool)': EventFragment;
    'LogCreateItem(uint256,address,uint256,uint256,address)': EventFragment;
    'OwnershipTransferred(address,address)': EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: 'LogBuyItem'): EventFragment;
  getEvent(nameOrSignatureOrTopic: 'LogChangeStatus'): EventFragment;
  getEvent(nameOrSignatureOrTopic: 'LogCreateItem'): EventFragment;
  getEvent(nameOrSignatureOrTopic: 'OwnershipTransferred'): EventFragment;
}

export interface LogBuyItemEventObject {
  itemId: BigNumber;
  nft: string;
  tokenId: BigNumber;
  price: BigNumber;
  seller: string;
  buyer: string;
}
export type LogBuyItemEvent = TypedEvent<
  [BigNumber, string, BigNumber, BigNumber, string, string],
  LogBuyItemEventObject
>;

export type LogBuyItemEventFilter = TypedEventFilter<LogBuyItemEvent>;

export interface LogChangeStatusEventObject {
  _itemID: BigNumber;
  _seller: string;
  _newStatus: boolean;
}
export type LogChangeStatusEvent = TypedEvent<
  [BigNumber, string, boolean],
  LogChangeStatusEventObject
>;

export type LogChangeStatusEventFilter = TypedEventFilter<LogChangeStatusEvent>;

export interface LogCreateItemEventObject {
  itemId: BigNumber;
  nft: string;
  tokenId: BigNumber;
  price: BigNumber;
  seller: string;
}
export type LogCreateItemEvent = TypedEvent<
  [BigNumber, string, BigNumber, BigNumber, string],
  LogCreateItemEventObject
>;

export type LogCreateItemEventFilter = TypedEventFilter<LogCreateItemEvent>;

export interface OwnershipTransferredEventObject {
  previousOwner: string;
  newOwner: string;
}
export type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  OwnershipTransferredEventObject
>;

export type OwnershipTransferredEventFilter = TypedEventFilter<OwnershipTransferredEvent>;

export interface Marketplace extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: MarketplaceInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(eventFilter: TypedEventFilter<TEvent>): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    buyItem(
      _itemId: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    changeItemStatus(
      _itemId: PromiseOrValue<BigNumberish>,
      _newStatus: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    feePercent(overrides?: CallOverrides): Promise<[BigNumber]>;

    getContractBalance(overrides?: CallOverrides): Promise<[BigNumber]>;

    getItemsCount(overrides?: CallOverrides): Promise<[BigNumber]>;

    getItemsSold(overrides?: CallOverrides): Promise<[BigNumber]>;

    getTotalPrice(
      _itemId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    items(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, string, BigNumber, BigNumber, string, boolean, boolean] & {
        itemId: BigNumber;
        nft: string;
        tokenId: BigNumber;
        price: BigNumber;
        seller: string;
        listed: boolean;
        sold: boolean;
      }
    >;

    itemsCount(overrides?: CallOverrides): Promise<[BigNumber] & { _value: BigNumber }>;

    itemsSold(overrides?: CallOverrides): Promise<[BigNumber] & { _value: BigNumber }>;

    makeItem(
      _nft: PromiseOrValue<string>,
      _tokenId: PromiseOrValue<BigNumberish>,
      _price: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setFeePercent(
      _feePercent: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    withdraw(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  buyItem(
    _itemId: PromiseOrValue<BigNumberish>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  changeItemStatus(
    _itemId: PromiseOrValue<BigNumberish>,
    _newStatus: PromiseOrValue<boolean>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  feePercent(overrides?: CallOverrides): Promise<BigNumber>;

  getContractBalance(overrides?: CallOverrides): Promise<BigNumber>;

  getItemsCount(overrides?: CallOverrides): Promise<BigNumber>;

  getItemsSold(overrides?: CallOverrides): Promise<BigNumber>;

  getTotalPrice(
    _itemId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  items(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, string, BigNumber, BigNumber, string, boolean, boolean] & {
      itemId: BigNumber;
      nft: string;
      tokenId: BigNumber;
      price: BigNumber;
      seller: string;
      listed: boolean;
      sold: boolean;
    }
  >;

  itemsCount(overrides?: CallOverrides): Promise<BigNumber>;

  itemsSold(overrides?: CallOverrides): Promise<BigNumber>;

  makeItem(
    _nft: PromiseOrValue<string>,
    _tokenId: PromiseOrValue<BigNumberish>,
    _price: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  owner(overrides?: CallOverrides): Promise<string>;

  renounceOwnership(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setFeePercent(
    _feePercent: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  transferOwnership(
    newOwner: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  withdraw(overrides?: Overrides & { from?: PromiseOrValue<string> }): Promise<ContractTransaction>;

  callStatic: {
    buyItem(_itemId: PromiseOrValue<BigNumberish>, overrides?: CallOverrides): Promise<void>;

    changeItemStatus(
      _itemId: PromiseOrValue<BigNumberish>,
      _newStatus: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<void>;

    feePercent(overrides?: CallOverrides): Promise<BigNumber>;

    getContractBalance(overrides?: CallOverrides): Promise<BigNumber>;

    getItemsCount(overrides?: CallOverrides): Promise<BigNumber>;

    getItemsSold(overrides?: CallOverrides): Promise<BigNumber>;

    getTotalPrice(
      _itemId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    items(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, string, BigNumber, BigNumber, string, boolean, boolean] & {
        itemId: BigNumber;
        nft: string;
        tokenId: BigNumber;
        price: BigNumber;
        seller: string;
        listed: boolean;
        sold: boolean;
      }
    >;

    itemsCount(overrides?: CallOverrides): Promise<BigNumber>;

    itemsSold(overrides?: CallOverrides): Promise<BigNumber>;

    makeItem(
      _nft: PromiseOrValue<string>,
      _tokenId: PromiseOrValue<BigNumberish>,
      _price: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    owner(overrides?: CallOverrides): Promise<string>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    setFeePercent(
      _feePercent: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    transferOwnership(newOwner: PromiseOrValue<string>, overrides?: CallOverrides): Promise<void>;

    withdraw(overrides?: CallOverrides): Promise<void>;
  };

  filters: {
    'LogBuyItem(uint256,address,uint256,uint256,address,address)'(
      itemId?: null,
      nft?: PromiseOrValue<string> | null,
      tokenId?: null,
      price?: null,
      seller?: PromiseOrValue<string> | null,
      buyer?: PromiseOrValue<string> | null
    ): LogBuyItemEventFilter;
    LogBuyItem(
      itemId?: null,
      nft?: PromiseOrValue<string> | null,
      tokenId?: null,
      price?: null,
      seller?: PromiseOrValue<string> | null,
      buyer?: PromiseOrValue<string> | null
    ): LogBuyItemEventFilter;

    'LogChangeStatus(uint256,address,bool)'(
      _itemID?: null,
      _seller?: null,
      _newStatus?: null
    ): LogChangeStatusEventFilter;
    LogChangeStatus(_itemID?: null, _seller?: null, _newStatus?: null): LogChangeStatusEventFilter;

    'LogCreateItem(uint256,address,uint256,uint256,address)'(
      itemId?: null,
      nft?: PromiseOrValue<string> | null,
      tokenId?: null,
      price?: null,
      seller?: PromiseOrValue<string> | null
    ): LogCreateItemEventFilter;
    LogCreateItem(
      itemId?: null,
      nft?: PromiseOrValue<string> | null,
      tokenId?: null,
      price?: null,
      seller?: PromiseOrValue<string> | null
    ): LogCreateItemEventFilter;

    'OwnershipTransferred(address,address)'(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;
  };

  estimateGas: {
    buyItem(
      _itemId: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    changeItemStatus(
      _itemId: PromiseOrValue<BigNumberish>,
      _newStatus: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    feePercent(overrides?: CallOverrides): Promise<BigNumber>;

    getContractBalance(overrides?: CallOverrides): Promise<BigNumber>;

    getItemsCount(overrides?: CallOverrides): Promise<BigNumber>;

    getItemsSold(overrides?: CallOverrides): Promise<BigNumber>;

    getTotalPrice(
      _itemId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    items(arg0: PromiseOrValue<BigNumberish>, overrides?: CallOverrides): Promise<BigNumber>;

    itemsCount(overrides?: CallOverrides): Promise<BigNumber>;

    itemsSold(overrides?: CallOverrides): Promise<BigNumber>;

    makeItem(
      _nft: PromiseOrValue<string>,
      _tokenId: PromiseOrValue<BigNumberish>,
      _price: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setFeePercent(
      _feePercent: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    withdraw(overrides?: Overrides & { from?: PromiseOrValue<string> }): Promise<BigNumber>;
  };

  populateTransaction: {
    buyItem(
      _itemId: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    changeItemStatus(
      _itemId: PromiseOrValue<BigNumberish>,
      _newStatus: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    feePercent(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getContractBalance(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getItemsCount(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getItemsSold(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getTotalPrice(
      _itemId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    items(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    itemsCount(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    itemsSold(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    makeItem(
      _nft: PromiseOrValue<string>,
      _tokenId: PromiseOrValue<BigNumberish>,
      _price: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setFeePercent(
      _feePercent: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    withdraw(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
