import Head from 'next/head';

type Props = {
  pageTitle: string;
};

const SEO = ({ pageTitle }: Props) => (
  <Head>
    <title> {pageTitle} || Leda - Jupiter based NFT Marketplace</title>
    <meta httpEquiv="x-ua-compatible" content="ie=edge" />
    <meta name="description" content="Generated by create next app" />
    <meta name="robots" content="noindex, follow" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <link rel="icon" href="/favicon.png" />
  </Head>
);

export default SEO;
