enum MintError {
  ContractEventNotFound = 0,
  ContractReceiptFailure = 1,
  IpfsMetadataFailure = 2,
  IpfsStoreFailure = 3,
  MintNftFailure = 4,
  MintNftUnsuccessful = 5,
  RequiredAddress = 6,
  RequiredBlobFile = 7,
  RequiredCid = 8,
  RequiredCollectionAddress = 9,
  RequiredDescription = 10,
  RequireDescription = 11,
  RequiredImageUrl = 12,
  RequiredIpfsObject = 13,
  RequiredName = 14,
  RequiredRoyalty = 15,
  RequiredTokenId = 16,
  RequireMintEvent = 17,
  RequireMintEventName = 18,
  RequireRoyalty = 19,
  RequireUrl = 20,
  StoreItemFailure = 21,
}

export default MintError;
